sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t zahaanjasani/containerization -f Dockerfile.dev .

script:
    - docker run -e CI=true zahaanjasani/containerization npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "containerization"
    env: "Containerization-env"
    bucket_name: "elasticbeanstalk-us-east-1-739265941623"
    bucket_path: "containerization"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    